### PR TITLE
70 django trying to get django to display and read our html files

### PR DESCRIPTION
**Pull request by KenichiroAnderson**
The website should work, cssfiles are to be fixed here in a bit but this is a separate issues, if there are any pages that don't link properly please either fix them or let me know!

### CODE REVIEW

**Comment by eremozdemir** [comment]
I saw you show it to me working well good work!

**Comment by KevinKim99** [comment]
looks good, no conflicts to be merged, good work!

**Comment by NathanIsCoding** [comment]
Thanks for getting the website to show up on django, looks good albiet a little bare-bones without the CSS, but we can get that worked out.

**Comment by EricSmith10** [comment]
Looks good! no conflicts and we will sort out the CSS. Good to merge

**Pull request merged**
