### PR TITLE
Artist Entries

### PR DESCRIPTION
**Pull request by EricSmith10**
added all all entries for the artists table and made a test to ensure they are all there. Also deleted some unnecessary files.

### CODE REVIEW

**Comment by KevinKim99** [comment]
looks like all needed information for artists are updated! 
good work!

**Comment by NathanIsCoding** [comment]
Looks good to me, happy to see you implemented some tests as well!

**Comment by eremozdemir** [comment]
tables look good! thanks for removing the test_remove_artist

**Review by KenichiroAnderson — COMMENTED** [review]
testing looks good, 30 might be a lot but should be ok for now

**Pull request merged**
