### PR TITLE
added testing for Concerts.html

### PR DESCRIPTION
**Pull request by KenichiroAnderson**
you will need jest in your vscode to run these tests but they do work and do create false concerts and artists and ensure that they are working. so this one is ready for push to main

### CODE REVIEW

**Comment by KenichiroAnderson** [comment]
sorry, i originally made this in main then realized that I cant do that, got to follow protocol

**Comment by EricSmith10** [comment]
thanks for making the tests Ken, looks good. Good comments as well

**Comment by NathanIsCoding** [comment]
Looks good, tests seem reasonable and code is clear.

**Comment by KevinKim99** [comment]
testing cases are well functioning, code is well written in neat way

**Pull request merged**
