### PR TITLE
Login save to clients table

### PR DESCRIPTION
**Pull request by KenichiroAnderson**

### CODE REVIEW

**Comment by KenichiroAnderson** [comment]
previously the login used a webpage user and key that would push it locally but not actually save the data or do anything of importance with it to sign up and login, now the data gets entered into the form, password gets hashed and then saved into the clients table. then when we log in we verify the form credentials, compare the usernames to other usernames in the table if we find it then we compare the password that is hashed, so we hash the entered password and compare it to the one in the database. so no direct comparison of the passwords is done

**Comment by KevinKim99** [comment]
I have checked that it works perfectly as it shows the client detail whom logged into the web! Good work!

**Comment by NathanIsCoding** [comment]
I checked through the code, everything looks like its been formatted well, good stuff.

**Comment by eremozdemir** [comment]
this is a great way to keep efficiency within the login process, good job!

**Pull request merged**
